# Finding the nth permutation matrix

Assume we have an $m \times{} n$ matrix.

\begin{bmatrix}
0 & 1 & 0 \\
1 & 0 & 0 \\
0 & 0 & 1
\end{bmatrix}


In [10]:
import numpy as np
import math

In [61]:
def nth_permutation_matrix(i, m = 3):
    available_positions = list(range(m))
    p_matrix = np.zeros((m,m))
    res      = i
    for row_index in range(m-1):
        # How many posibilities there are in next rows?
        n1f      = math.factorial(m - row_index -1)
        # What is the index of this row?
        res      = math.floor(i / n1f)
        # The index may have already been used in a previous row.
        # take one from our list of indexes
        position = available_positions[res]
        del available_positions[res]

        p_matrix[row_index,position] = 1
        # our next iteration through the loop will be constrained by 
        i = i - (res * n1f)
        
    p_matrix[m-1, available_positions[0]] = 1
    return p_matrix
    
    # for row_index in range(m):
        
nth_permutation(6, 4)

array([[ 0.,  1.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [68]:
upto = 4
for i in range(math.factorial(upto)):
    print('next up: {0}'.format(i))
    print(nth_permutation(i, upto))

next up: 0
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
next up: 1
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  1.  0.]]
next up: 2
[[ 1.  0.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  0.  1.]]
next up: 3
[[ 1.  0.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  1.  0.  0.]]
next up: 4
[[ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]]
next up: 5
[[ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  1.  0.]
 [ 0.  1.  0.  0.]]
next up: 6
[[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
next up: 7
[[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  1.  0.]]
next up: 8
[[ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]]
next up: 9
[[ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]
 [ 1.  0.  0.  0.]]
next up: 10
[[ 0.  1.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  1.  0.]]
next up: 11
[[ 0.  1.  0.  0.]
